/*
We believe, the class name must be unique. 
If there is a conflicting class name in this file,
it means you have to rename it to something more unique.
*/
export 'package:fhe_template/config.dart';
export 'package:fhe_template/firebase_options.dart';
export 'package:fhe_template/module/00_statemanagement/a_counter/controller/counter_controller.dart';
export 'package:fhe_template/module/00_statemanagement/a_counter/view/counter_view.dart';
export 'package:fhe_template/module/00_statemanagement/b_enable_or_disable/controller/enable_or_disable_controller.dart';
export 'package:fhe_template/module/00_statemanagement/b_enable_or_disable/view/enable_or_disable_view.dart';
export 'package:fhe_template/module/00_statemanagement/c_loading/controller/loading_controller.dart';
export 'package:fhe_template/module/00_statemanagement/c_loading/view/loading_view.dart';
export 'package:fhe_template/module/00_statemanagement/controller/home_controller.dart';
export 'package:fhe_template/module/00_statemanagement/d_visibility/controller/visibility_controller.dart';
export 'package:fhe_template/module/00_statemanagement/d_visibility/view/visibility_view.dart';
export 'package:fhe_template/module/00_statemanagement/e_Uppere_case & Lower Case/controller/Uppercase & Lower Case_controller.dart';
export 'package:fhe_template/module/00_statemanagement/e_Uppere_case & Lower Case/view/Uppercase & Lower Case_view.dart';
export 'package:fhe_template/module/00_statemanagement/f_allanimation/controller/allanimation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/f_allanimation/view/allanimation_view.dart';
export 'package:fhe_template/module/00_statemanagement/g_animationbyMouseEvent/controller/animationbyMouseEvent_controller.dart';
export 'package:fhe_template/module/00_statemanagement/g_animationbyMouseEvent/view/animationbyMouseEvent_view.dart';
export 'package:fhe_template/module/00_statemanagement/h_slideanimation/controller/slideanimation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/h_slideanimation/view/slideanimation_view.dart';
export 'package:fhe_template/module/00_statemanagement/i_scaleAnimation/controller/scaleAnimation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/i_scaleAnimation/view/scaleAnimation_view.dart';
export 'package:fhe_template/module/00_statemanagement/j_scaleAnimationBySlideValue/controller/scaleAnimationBySlideValue_controller.dart';
export 'package:fhe_template/module/00_statemanagement/j_scaleAnimationBySlideValue/view/scaleAnimationBySlideValue_view.dart';
export 'package:fhe_template/module/00_statemanagement/k_digitalclock/controller/digitalclock_controller.dart';
export 'package:fhe_template/module/00_statemanagement/k_digitalclock/view/digitalclock_view.dart';
export 'package:fhe_template/module/00_statemanagement/k_rotateAnimation/controller/rotateAnimation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/k_rotateAnimation/view/rotateAnimation_view.dart';
export 'package:fhe_template/module/00_statemanagement/l_fadeAnimation/controller/fadeAnimation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/l_fadeAnimation/view/fadeAnimation_view.dart';
export 'package:fhe_template/module/00_statemanagement/m_horizontalCategoryList/controller/horizontalCategoryList_controller.dart';
export 'package:fhe_template/module/00_statemanagement/m_horizontalCategoryList/view/horizontalCategoryList_view.dart';
export 'package:fhe_template/module/00_statemanagement/m_verticalCategoryList/controller/verticalCategoryList_controller.dart';
export 'package:fhe_template/module/00_statemanagement/m_verticalCategoryList/view/verticalCategoryList_view.dart';
export 'package:fhe_template/module/00_statemanagement/n_filterlist/controller/filterlist_controller.dart';
export 'package:fhe_template/module/00_statemanagement/n_filterlist/view/filterlist_view.dart';
export 'package:fhe_template/module/00_statemanagement/o_categoryInWrap/controller/categoryInWrap_controller.dart';
export 'package:fhe_template/module/00_statemanagement/o_categoryInWrap/view/categoryInWrap_view.dart';
export 'package:fhe_template/module/00_statemanagement/p_chatList/controller/chatList_controller.dart';
export 'package:fhe_template/module/00_statemanagement/p_chatList/view/chatList_view.dart';
export 'package:fhe_template/module/00_statemanagement/q_navigation/controller/navigation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/q_navigation/view/navigation_view.dart';
export 'package:fhe_template/module/00_statemanagement/r_crud/controller/crud_controller.dart';
export 'package:fhe_template/module/00_statemanagement/r_crud/view/crud_view.dart';
export 'package:fhe_template/module/00_statemanagement/s_repeatAnimation/controller/repeatAnimation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/s_repeatAnimation/view/repeatAnimation_view.dart';
export 'package:fhe_template/module/00_statemanagement/t_navigationWithSlideAnimation/controller/navigationWithSlideAnimation_controller.dart';
export 'package:fhe_template/module/00_statemanagement/t_navigationWithSlideAnimation/view/navigationWithSlideAnimation_view.dart';
export 'package:fhe_template/module/00_statemanagement/u_scrollGetx/controller/scrollGetx_controller.dart';
export 'package:fhe_template/module/00_statemanagement/u_scrollGetx/view/scrollGetx_view.dart';
export 'package:fhe_template/module/00_statemanagement/v_theme/controller/theme_controller.dart';
export 'package:fhe_template/module/00_statemanagement/v_theme/theme/dark_theme.dart';
export 'package:fhe_template/module/00_statemanagement/v_theme/theme/light_theme.dart';
export 'package:fhe_template/module/00_statemanagement/v_theme/theme/purple_theme.dart';
export 'package:fhe_template/module/00_statemanagement/v_theme/view/theme_view.dart';
export 'package:fhe_template/module/00_statemanagement/view/home_view.dart';
export 'package:fhe_template/module/00_statemanagement/w_notificationsLocal/controller/notificationsLocal_controller.dart';
export 'package:fhe_template/module/00_statemanagement/w_notificationsLocal/view/notificationsLocal_view.dart';
export 'package:fhe_template/module/00_statemanagement/w_notificationsLocal/widget/local_notification.dart';
export 'package:fhe_template/module/00_statemanagement/w_notificationsLocal/widget/notifications.dart';
export 'package:fhe_template/module/00_statemanagement/widget/expension_tile.dart';
export 'package:fhe_template/module/00_statemanagement/widget/tutorial_navigation_item.dart';
export 'package:fhe_template/module/01_form/a_form reuseable/controller/form reuseable_controller.dart';
export 'package:fhe_template/module/01_form/a_form reuseable/view/form reuseable_view.dart';
export 'package:fhe_template/module/01_form/b_form origin/controller/form origin_controller.dart';
export 'package:fhe_template/module/01_form/b_form origin/view/form origin_view.dart';
export 'package:fhe_template/module/01_form/c_login/controller/login_controller.dart';
export 'package:fhe_template/module/01_form/c_login/view/login_view.dart';
export 'package:fhe_template/module/01_form/controller/form_controller.dart';
export 'package:fhe_template/module/01_form/d_sign up/controller/sign up_controller.dart';
export 'package:fhe_template/module/01_form/d_sign up/view/sign up_view.dart';
export 'package:fhe_template/module/01_form/e_reset password/controller/reset password_controller.dart';
export 'package:fhe_template/module/01_form/e_reset password/view/reset password_view.dart';
export 'package:fhe_template/module/01_form/f_edit profile/controller/edit profile_controller.dart';
export 'package:fhe_template/module/01_form/f_edit profile/view/edit profile_view.dart';
export 'package:fhe_template/module/01_form/g_product form/controller/product form_controller.dart';
export 'package:fhe_template/module/01_form/g_product form/view/product form_view.dart';
export 'package:fhe_template/module/01_form/h_review form/controller/review form_controller.dart';
export 'package:fhe_template/module/01_form/h_review form/view/review form_view.dart';
export 'package:fhe_template/module/01_form/i_checkout form/controller/checkout form_controller.dart';
export 'package:fhe_template/module/01_form/i_checkout form/view/checkout form_view.dart';
export 'package:fhe_template/module/01_form/j_filter dialog form/controller/filter dialog form_controller.dart';
export 'package:fhe_template/module/01_form/j_filter dialog form/view/filter dialog form_view.dart';
export 'package:fhe_template/module/01_form/k_filter bottom sheet/controller/filter bottom sheet_controller.dart';
export 'package:fhe_template/module/01_form/k_filter bottom sheet/view/filter bottom sheet_view.dart';
export 'package:fhe_template/module/01_form/l_sliding form/controller/sliding form_controller.dart';
export 'package:fhe_template/module/01_form/l_sliding form/view/sliding form_view.dart';
export 'package:fhe_template/module/01_form/view/form_view.dart';
export 'package:fhe_template/module/02_http/a_login http/controller/login http_controller.dart';
export 'package:fhe_template/module/02_http/a_login http/view/login http_view.dart';
export 'package:fhe_template/module/02_http/b_product list/controller/product list_controller.dart';
export 'package:fhe_template/module/02_http/b_product list/view/product list_view.dart';
export 'package:fhe_template/module/02_http/c_dashboard/controller/dashboard_controller.dart';
export 'package:fhe_template/module/02_http/c_dashboard/view/dashboard_view.dart';
export 'package:fhe_template/module/02_http/controller/http_controller.dart';
export 'package:fhe_template/module/02_http/d_image galleries/controller/image galleries_controller.dart';
export 'package:fhe_template/module/02_http/d_image galleries/view/image galleries_view.dart';
export 'package:fhe_template/module/02_http/e_static card/controller/static card_controller.dart';
export 'package:fhe_template/module/02_http/e_static card/view/static card_view.dart';
export 'package:fhe_template/module/02_http/f_line chart/controller/line chart_controller.dart';
export 'package:fhe_template/module/02_http/f_line chart/view/line chart_view.dart';
export 'package:fhe_template/module/02_http/g_pie chart/controller/pie chart_controller.dart';
export 'package:fhe_template/module/02_http/g_pie chart/view/pie chart_view.dart';
export 'package:fhe_template/module/02_http/h_todolist/controller/todolist_controller.dart';
export 'package:fhe_template/module/02_http/h_todolist/view/todolist_view.dart';
export 'package:fhe_template/module/02_http/i_product CRUD/controller/product CRUD_controller.dart';
export 'package:fhe_template/module/02_http/i_product CRUD/view/product CRUD_view.dart';
export 'package:fhe_template/module/02_http/j_Map Marker/controller/Map Marker_controller.dart';
export 'package:fhe_template/module/02_http/j_Map Marker/view/Map Marker_view.dart';
export 'package:fhe_template/module/02_http/product form http/controller/product form http_controller.dart';
export 'package:fhe_template/module/02_http/product form http/view/product form http_view.dart';
export 'package:fhe_template/module/02_http/view/http_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/controller/ui_dashboard_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard1/controller/uk_dashboard1_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard1/view/uk_dashboard1_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard10/controller/uk_dashboard10_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard10/view/uk_dashboard10_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard11/controller/uk_dashboard11_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard11/view/uk_dashboard11_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard12/controller/uk_dashboard12_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard12/view/uk_dashboard12_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard13/controller/uk_dashboard13_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard13/view/uk_dashboard13_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard14/controller/uk_dashboard14_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard14/view/uk_dashboard14_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard15/controller/uk_dashboard15_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard15/view/uk_dashboard15_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard16/controller/uk_dashboard16_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard16/view/uk_dashboard16_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard17/controller/uk_dashboard17_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard17/view/uk_dashboard17_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard18/controller/uk_dashboard18_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard18/view/uk_dashboard18_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard19/controller/uk_dashboard19_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard19/view/uk_dashboard19_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard2/controller/uk_dashboard2_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard2/view/uk_dashboard2_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard20/controller/uk_dashboard20_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard20/view/uk_dashboard20_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard3/controller/uk_dashboard3_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard3/view/uk_dashboard3_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard4/controller/uk_dashboard4_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard4/view/uk_dashboard4_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard5/controller/uk_dashboard5_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard5/view/uk_dashboard5_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard6/controller/uk_dashboard6_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard6/view/uk_dashboard6_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard7/controller/uk_dashboard7_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard7/view/uk_dashboard7_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard8/controller/uk_dashboard8_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard8/view/uk_dashboard8_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard9/controller/uk_dashboard9_controller.dart';
export 'package:fhe_template/module/03_ui_dashboard/pages/uk_dashboard9/view/uk_dashboard9_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/view/ui_dashboard_view.dart';
export 'package:fhe_template/module/03_ui_dashboard/widget/uk_dashboard_menu_item.dart';
export 'package:fhe_template/module/04_widget/controller/widget_controller.dart';
export 'package:fhe_template/module/04_widget/pages/uk_button/controller/uk_button_controller.dart';
export 'package:fhe_template/module/04_widget/pages/uk_button/view/uk_button_view.dart';
export 'package:fhe_template/module/04_widget/pages/uk_carousel/controller/uk_carousel_controller.dart';
export 'package:fhe_template/module/04_widget/pages/uk_carousel/view/uk_carousel_view.dart';
export 'package:fhe_template/module/04_widget/view/widget_view.dart';
export 'package:fhe_template/module/05_apps/controller/apps_controller.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/main.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/_home_screen.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/drawer/_drawer_screen.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/drawer/drawer_menu.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/drawer/drawer_profile.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/trending/_trending_screen.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/trending/trending_app_bar.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/trending/trending_body.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/trending/widgets/article_card.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/trending/widgets/dot_indicators.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/screens/trending/widgets/trending_profile.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/shared/colors.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/shared/custom_system_ui_overlay_style.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/shared/data/data_source.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/shared/data/models/article.dart';
export 'package:fhe_template/module/05_apps/main/lib_articale/shared/sizes.dart';
export 'package:fhe_template/module/05_apps/view/apps_view.dart';

export 'package:fhe_template/module/date time stream/controller/date time stream_controller.dart';
export 'package:fhe_template/module/date time stream/view/date time stream_view.dart';
export 'package:fhe_template/navigationNew/controller/navigationNew_controller.dart';
export 'package:fhe_template/navigationNew/view/navigationNew_view.dart';
export 'package:fhe_template/services/upp&lowcase.dart';
export 'package:fhe_template/session.dart';
export 'package:fhe_template/setup.dart';
export 'package:fhe_template/shared/theme/theme.dart';
export 'package:fhe_template/shared/theme/theme_constants.dart';
export 'package:fhe_template/shared/theme/theme_dark.dart';
export 'package:fhe_template/shared/theme/theme_size.dart';
export 'package:fhe_template/shared/util/dialog/confirmation_dialog.dart';
export 'package:fhe_template/shared/util/dialog/show_info_dialog.dart';
export 'package:fhe_template/shared/util/focus_helper/focus_helper.dart';
export 'package:fhe_template/shared/util/format/format.dart';
export 'package:fhe_template/shared/util/input/input.dart';
export 'package:fhe_template/shared/util/random_image/random_image.dart';
export 'package:fhe_template/shared/util/responsive/responsive.dart';
export 'package:fhe_template/shared/util/show_loading/show_loading.dart';
export 'package:fhe_template/shared/util/url_launcher/url_launcher.dart';
export 'package:fhe_template/shared/util/validator/validator.dart';
export 'package:fhe_template/shared/widget/button/action_button.dart';
export 'package:fhe_template/shared/widget/button/action_button_with_options.dart';
export 'package:fhe_template/shared/widget/button/button.dart';
export 'package:fhe_template/shared/widget/button/floating_action.dart';
export 'package:fhe_template/shared/widget/button/outline_button.dart';
export 'package:fhe_template/shared/widget/button/outline_danger_button.dart';
export 'package:fhe_template/shared/widget/button/outline_icon_button.dart';
export 'package:fhe_template/shared/widget/button/outline_success_button.dart';
export 'package:fhe_template/shared/widget/carousel/carousel.dart';
export 'package:fhe_template/shared/widget/category_picker/category_picker.dart';
export 'package:fhe_template/shared/widget/category_picker/tag_picker.dart';
export 'package:fhe_template/shared/widget/checkbox/checkbox.dart';
export 'package:fhe_template/shared/widget/combo/combo.dart';
export 'package:fhe_template/shared/widget/datepicker/datepicker.dart';
export 'package:fhe_template/shared/widget/datepicker/timepicker.dart';
export 'package:fhe_template/shared/widget/form/__form_detail_example.dart';
export 'package:fhe_template/shared/widget/form/__form_example.dart';
export 'package:fhe_template/shared/widget/form/__form_example_non_reuseable.dart';
export 'package:fhe_template/shared/widget/form/__form_snippet.dart';
export 'package:fhe_template/shared/widget/form/autocomplete.dart';
export 'package:fhe_template/shared/widget/form/check.dart';
export 'package:fhe_template/shared/widget/form/datepicker.dart';
export 'package:fhe_template/shared/widget/form/dropdown.dart';
export 'package:fhe_template/shared/widget/form/image_picker.dart';
export 'package:fhe_template/shared/widget/form/numberfield.dart';
export 'package:fhe_template/shared/widget/form/radio.dart';
export 'package:fhe_template/shared/widget/form/switch.dart';
export 'package:fhe_template/shared/widget/form/textarea.dart';
export 'package:fhe_template/shared/widget/form/textfield.dart';
export 'package:fhe_template/shared/widget/form/timepicker.dart';
export 'package:fhe_template/shared/widget/image_picker/custom_image_builder.dart';
export 'package:fhe_template/shared/widget/image_picker/image_picker.dart';
export 'package:fhe_template/shared/widget/image_picker/image_picker_controller.dart';
export 'package:fhe_template/shared/widget/image_picker/network_image.dart';
export 'package:fhe_template/shared/widget/list/list_view.dart';
export 'package:fhe_template/shared/widget/loading/image_loading.dart';
export 'package:fhe_template/shared/widget/location_picker/location_picker copy.dart';
export 'package:fhe_template/shared/widget/location_picker/location_picker.dart';
export 'package:fhe_template/shared/widget/location_picker/location_picker_map_view.dart';
export 'package:fhe_template/shared/widget/location_picker/map_viewer.dart';
export 'package:fhe_template/shared/widget/navigation/navigation.dart';
export 'package:fhe_template/shared/widget/radio/radio.dart';
export 'package:fhe_template/shared/widget/radio/switch.dart';
export 'package:fhe_template/shared/widget/rating/rating.dart';
export 'package:fhe_template/shared/widget/rating/rating_field.dart';
export 'package:fhe_template/shared/widget/slider/slider.dart';
export 'package:fhe_template/shared/widget/textfield/autocomplete.dart';
export 'package:fhe_template/shared/widget/textfield/searchfield.dart';
export 'package:fhe_template/shared/widget/textfield/textarea.dart';
export 'package:fhe_template/shared/widget/textfield/textfield.dart';
export 'package:fhe_template/shared/widget/typography/heading.dart';
export 'package:fhe_template/shared/widget/uncategorized/snippet_container/snippet_container.dart';
export 'package:fhe_template/shared/widget/uncategorized/snippet_container/snippet_header.dart';
export 'package:fhe_template/shared/widget/uncategorized/widget_demo/widget_demo.dart';
export 'package:fhe_template/state_util.dart';
