// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KF9Oom9eo9fFQ4R4DbjeMm_WmfXllUw',
    appId: '1:214319344206:web:b0ec944ffdc0f1e255311f',
    messagingSenderId: '214319344206',
    projectId: 'allgetxmethode',
    authDomain: 'allgetxmethode.firebaseapp.com',
    storageBucket: 'allgetxmethode.appspot.com',
    measurementId: 'G-H5NYTL31G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcXinYQNW2JR39EgTWSm5loNriP36aSaA',
    appId: '1:214319344206:android:775c087489a6339255311f',
    messagingSenderId: '214319344206',
    projectId: 'allgetxmethode',
    storageBucket: 'allgetxmethode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWN222jV4gid2UiB_i9uyfPgxQOcFUeE',
    appId: '1:214319344206:ios:b802f9277aea1e7455311f',
    messagingSenderId: '214319344206',
    projectId: 'allgetxmethode',
    storageBucket: 'allgetxmethode.appspot.com',
    androidClientId:
        '214319344206-1igldbhe9rlug6b5aufreeirojm1js2d.apps.googleusercontent.com',
    iosClientId:
        '214319344206-mj1q5n9enj6qh5puip5mebf01uuuv4a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.blankFireSetstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWN222jV4gid2UiB_i9uyfPgxQOcFUeE',
    appId: '1:214319344206:ios:b802f9277aea1e7455311f',
    messagingSenderId: '214319344206',
    projectId: 'allgetxmethode',
    storageBucket: 'allgetxmethode.appspot.com',
    androidClientId:
        '214319344206-1igldbhe9rlug6b5aufreeirojm1js2d.apps.googleusercontent.com',
    iosClientId:
        '214319344206-mj1q5n9enj6qh5puip5mebf01uuuv4a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.blankFireSetstate',
  );
}
